const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

async function main() {
  console.log("Seeding 32 Adds Buzz banner advertisements with FULL_WIDTH and HALF_WIDTH formats...");

  // Reset existing ads so clean formatted ads are stored
  await prisma.advertisement.deleteMany({});

  const adsToSeed = [
    {
      name: "GLOBAL EDUCATION FAIR 2026 - Study in UK, USA, Canada & Australia",
      imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://ilmika.com/events/global-fair-2026",
      placement: "BOTH",
      format: "QUAD_GRID",
      displayOrder: 1,
      isActive: true,
    },
    {
      name: "SCHOLARSHIPS DIRECTORY 2026 - Up to 100% Tuition Grants Worldwide",
      imageUrl: "https://images.unsplash.com/photo-1541829070764-84a7d30dd3f3?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://ilmika.com/scholarships",
      placement: "BOTH",
      format: "QUAD_GRID",
      displayOrder: 2,
      isActive: true,
    },
    {
      name: "OXFORD SCHOLARSHIP PORTAL - International Study",
      imageUrl: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://ox.ac.uk/scholarships",
      placement: "BOTH",
      format: "QUAD_GRID",
      displayOrder: 3,
      isActive: true,
    },
    {
      name: "HARVARD LEADERSHIP PROGRAM 2026",
      imageUrl: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://harvard.edu/programs",
      placement: "BOTH",
      format: "QUAD_GRID",
      displayOrder: 4,
      isActive: true,
    },
    {
      name: "NITTE Deemed to be University - Admissions 2026",
      imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://apply.nitte.edu.in",
      placement: "BOTH",
      format: "FULL_WIDTH",
      displayOrder: 3,
      isActive: true,
    },
    {
      name: "Manipal Academy of Higher Education - Global Intake",
      imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://manipal.edu",
      placement: "BOTH",
      format: "FULL_WIDTH",
      displayOrder: 2,
      isActive: true,
    },
    {
      name: "St. Joseph Engineering College - B.Tech / M.Tech",
      imageUrl: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://sjec.ac.in",
      placement: "BOTH",
      format: "HALF_WIDTH",
      displayOrder: 3,
      isActive: true,
    },
    {
      name: "YAMUNA HOMES & DESIGN - Student Living",
      imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://yamunahomes.com",
      placement: "BOTH",
      format: "HALF_WIDTH",
      displayOrder: 4,
      isActive: true,
    },
    {
      name: "PARADISE PROPERTIES - Student Residences",
      imageUrl: "https://images.unsplash.com/photo-1541829070764-84a7d30dd3f3?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://paradiseproperties.in",
      placement: "BOTH",
      format: "FULL_WIDTH",
      displayOrder: 5,
      isActive: true,
    },
    {
      name: "Seoul National University - Fall 2026 Admissions",
      imageUrl: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://useoul.edu",
      placement: "BOTH",
      format: "FULL_WIDTH",
      displayOrder: 6,
      isActive: true,
    },
    {
      name: "University of Melbourne - Global Excellence Grant",
      imageUrl: "https://images.unsplash.com/photo-1576495199011-eb94736d05d6?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://unimelb.edu.au",
      placement: "BOTH",
      format: "HALF_WIDTH",
      displayOrder: 7,
      isActive: true,
    },
    {
      name: "IIT Bombay - Innovation Incubator",
      imageUrl: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://iitb.ac.in",
      placement: "BOTH",
      format: "HALF_WIDTH",
      displayOrder: 8,
      isActive: true,
    },
    {
      name: "Warwick Business School - Executive MBA Grants 2026",
      imageUrl: "https://images.unsplash.com/photo-1513258496099-48168024aec0?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://wbs.ac.uk",
      placement: "BOTH",
      format: "FULL_WIDTH",
      displayOrder: 9,
      isActive: true,
    },
    {
      name: "Stanford University - AI & CS Fellowships",
      imageUrl: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://stanford.edu",
      placement: "BOTH",
      format: "FULL_WIDTH",
      displayOrder: 10,
      isActive: true,
    },
    {
      name: "Yenepoya University - Health Sciences",
      imageUrl: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://yenepoya.edu.in",
      placement: "BOTH",
      format: "HALF_WIDTH",
      displayOrder: 11,
      isActive: true,
    },
    {
      name: "Father Muller Medical - MBBS Intake",
      imageUrl: "https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://fathermuller.edu.in",
      placement: "BOTH",
      format: "HALF_WIDTH",
      displayOrder: 12,
      isActive: true,
    },
    {
      name: "Mangalore University - PG Degree Admissions",
      imageUrl: "https://images.unsplash.com/photo-1492538368677-f6e0afe31dcc?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://mangaloreuniversity.ac.in",
      placement: "BOTH",
      format: "FULL_WIDTH",
      displayOrder: 13,
      isActive: true,
    },
    {
      name: "Canara Engineering College - AI & Data Science B.Tech",
      imageUrl: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://canaraengg.in",
      placement: "BOTH",
      format: "FULL_WIDTH",
      displayOrder: 14,
      isActive: true,
    },
    {
      name: "Sahyadri College - Engineering Placements",
      imageUrl: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://sahyadri.edu.in",
      placement: "BOTH",
      format: "HALF_WIDTH",
      displayOrder: 15,
      isActive: true,
    },
    {
      name: "NITK Surathkal - B.Tech Cutoffs",
      imageUrl: "https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://nitk.ac.in",
      placement: "BOTH",
      format: "HALF_WIDTH",
      displayOrder: 16,
      isActive: true,
    },
    {
      name: "AJ Institute of Medical Sciences - Clinical Seats",
      imageUrl: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://ajims.edu.in",
      placement: "BOTH",
      format: "FULL_WIDTH",
      displayOrder: 17,
      isActive: true,
    },
    {
      name: "SDM College of Business Management - MBA & BBA Intake",
      imageUrl: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://sdm.ac.in",
      placement: "BOTH",
      format: "FULL_WIDTH",
      displayOrder: 18,
      isActive: true,
    },
    {
      name: "St. Aloysius University - Autonomous Degrees",
      imageUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://staloysius.edu.in",
      placement: "BOTH",
      format: "HALF_WIDTH",
      displayOrder: 19,
      isActive: true,
    },
    {
      name: "Srinivas University - Robotics B.Tech",
      imageUrl: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://srinivasuniversity.edu.in",
      placement: "BOTH",
      format: "HALF_WIDTH",
      displayOrder: 20,
      isActive: true,
    },
    {
      name: "Alva's Education Foundation - Sports Scholarship",
      imageUrl: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://alvas.org",
      placement: "BOTH",
      format: "FULL_WIDTH",
      displayOrder: 21,
      isActive: true,
    },
    {
      name: "Expert Coaching Institute - NEET & JEE Prep",
      imageUrl: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://expertclasses.org",
      placement: "BOTH",
      format: "FULL_WIDTH",
      displayOrder: 22,
      isActive: true,
    },
    {
      name: "Allen Career Institute - Entrance Prep",
      imageUrl: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://allen.ac.in",
      placement: "BOTH",
      format: "HALF_WIDTH",
      displayOrder: 23,
      isActive: true,
    },
    {
      name: "Mahesh PU College - PCMB Batches",
      imageUrl: "https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://maheshpucollege.org",
      placement: "BOTH",
      format: "HALF_WIDTH",
      displayOrder: 24,
      isActive: true,
    },
    {
      name: "Bearys Institute of Technology - Architecture & Engg",
      imageUrl: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://bitmangalore.edu.in",
      placement: "BOTH",
      format: "FULL_WIDTH",
      displayOrder: 25,
      isActive: true,
    },
    {
      name: "PA College of Engineering - Biotech B.Tech",
      imageUrl: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://pace.edu.in",
      placement: "BOTH",
      format: "FULL_WIDTH",
      displayOrder: 26,
      isActive: true,
    },
    {
      name: "NGSM Institute - B.Pharm & M.Pharm",
      imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://nitte.edu.in/ngsmips",
      placement: "BOTH",
      format: "HALF_WIDTH",
      displayOrder: 27,
      isActive: true,
    },
    {
      name: "KMC Manipal - Medical Fellowships",
      imageUrl: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://manipal.edu/kmc-manipal",
      placement: "BOTH",
      format: "HALF_WIDTH",
      displayOrder: 28,
      isActive: true,
    },
    {
      name: "Global Overseas Education - Visa Advisory",
      imageUrl: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://globaloverseas.org",
      placement: "BOTH",
      format: "FULL_WIDTH",
      displayOrder: 29,
      isActive: true,
    },
    {
      name: "EduWise Abroad - UK Scholarships",
      imageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://eduwiseabroad.com",
      placement: "BOTH",
      format: "FULL_WIDTH",
      displayOrder: 30,
      isActive: true,
    },
    {
      name: "Study in Japan - MEXT Grants",
      imageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://studyinjapan.go.jp",
      placement: "BOTH",
      format: "HALF_WIDTH",
      displayOrder: 31,
      isActive: true,
    },
    {
      name: "Erasmus Mundus - EU Fellowships",
      imageUrl: "https://images.unsplash.com/photo-1526772662000-3f88f10405ff?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://erasmus-plus.ec.europa.eu",
      placement: "BOTH",
      format: "HALF_WIDTH",
      displayOrder: 32,
      isActive: true,
    },
  ];

  for (const adData of adsToSeed) {
    await prisma.advertisement.create({ data: adData });
  }

  console.log(`Successfully seeded ${adsToSeed.length} formatted ad banners!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
